apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-flyte-data
  namespace: flyte-preflight
spec:
  backoffLimit: 20
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-bucket
          image: minio/mc:RELEASE.2025-08-13T08-35-41Z
          command: ["/bin/sh", "-ec"]
          args:
            - |
              until mc alias set local http://minio:9000 minio flyte-preflight-local-only; do
                sleep 2
              done
              mc mb --ignore-existing local/flyte-data
